apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-order-canary
  namespace: production
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-order
        env: canary
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - image: gcr.io/absolute-text-251105/piggy1-order:v4
        name: piggyback-prod-runner-order
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/secret.json
        resources:
          limits:
            memory: "384Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-order
          containerPort: 8088
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8088
status: {}
