apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-order-production
  namespace: production
spec:
  replicas: 2
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-order
        env: production
    spec:
      containers:
      - image: gcr.io/omega-palace-254907/piggy1-order:v4
        name: piggyback-prod-runner-order
        env:
          - name: JASYPT_ENCRYPTOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jasypt-password
                key: password
        resources:
          limits:
            memory: "384Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-order
          containerPort: 8088
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8088
status: {}
